package com.stelinno.demo.gcp;

import java.util.List;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.ObjectifyFactory;
import com.googlecode.objectify.ObjectifyService;
import com.googlecode.objectify.Result;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.*;


import static com.googlecode.objectify.ObjectifyService.ofy;

/***
 * https://github.com/objectify/objectify/wiki
 * @author Stelinno
 *
 */
public class ParcelService {
	public ParcelService(){
		ObjectifyService.begin(); //run();
		ObjectifyService.register(Parcel.class);
		new ObjectifyFactory().register(Parcel.class);
    }
	
	public void insertNew() {
		
		Parcel service = new Parcel("12312");
		ofy().save().entity(service).now();    // async without the now()
	}
	
	public Parcel read() {
		
		Parcel serviceFetched = ofy().load().type(Parcel.class).filter("trackAndTraceNo", "12312").first().now();
		return serviceFetched;
	}
	
	private void doItAll() {
		
		Parcel service = new Parcel("12312");
		ofy().save().entity(service).now();    // async without the now()
		
		Parcel serviceFetched = ofy().load().type(Parcel.class).filter("trackAndTraceNo", "12312").first().now();

		//assert service.id != null;    // id was autogenerated

		// More likely this is what you will type
		//Service fetched2 = ofy().load().type(Service.class).id(service.id).now();
		
		/*
		 * Car car = ofy().load().type(Car.class).filter("vin", "123456789").first().now();

// The Query itself is Iterable
Query<Car> q = ofy().load().type(Car.class).filter("vin >", "123456789");
for (Car car: q) {
    System.out.println(car.toString());
}
		 */

		// Or you can issue a query
		//Service fetched3 = ofy().load().type(Service.class).filter("license", "2FAST").first().now();

		// Change some data and write it
		//porsche.color = BLUE;
		//ofy().save().entity(porsche).now();    // async without the now()

		// Delete it
		//ofy().delete().entity(porsche).now();    // async without the now()
	}
}
